import { useRef, useState } from 'react';
import { motion } from 'framer-motion';
import { Download, Share2, Leaf, Globe, TreePine, Award } from 'lucide-react';
import { useTwin } from '../../context/TwinContext';
import { GlassCard, Button } from '../shared/UIComponents';

export default function ShareCard() {
  const { results } = useTwin();
  const cardRef = useRef(null);
  const [isGenerating, setIsGenerating] = useState(false);

  if (!results) return null;

  const { carbon, ecoScore, earthsNeeded, waterFootprint } = results;
  const treesEquiv = Math.round((carbon.total / 1000) * 45);

  const getClimateRank = () => {
    if (ecoScore >= 80) return { label: 'Climate Champion', color: 'text-emerald-400' };
    if (ecoScore >= 60) return { label: 'Eco Warrior', color: 'text-teal-400' };
    if (ecoScore >= 40) return { label: 'Green Learner', color: 'text-yellow-400' };
    return { label: 'Climate Explorer', color: 'text-orange-400' };
  };

  const rank = getClimateRank();

  const handleDownload = async () => {
    setIsGenerating(true);
    try {
      const html2canvas = (await import('html2canvas')).default;
      const canvas = await html2canvas(cardRef.current, {
        backgroundColor: '#0f172a',
        scale: 2,
        useCORS: true,
      });

      const link = document.createElement('a');
      link.download = 'ecotwin-climate-card.png';
      link.href = canvas.toDataURL('image/png');
      link.click();
    } catch (error) {
      console.error('Failed to generate image:', error);
    }
    setIsGenerating(false);
  };

  return (
    <div className="space-y-6">
      <h3 className="text-xl font-bold text-white text-center">
        Your Climate Card
      </h3>

      {/* Card Preview */}
      <div className="flex justify-center">
        <div
          ref={cardRef}
          className="w-full max-w-md rounded-2xl overflow-hidden"
          style={{
            background: 'linear-gradient(135deg, #0f172a 0%, #1e293b 50%, #0f172a 100%)',
            border: '1px solid rgba(255, 255, 255, 0.1)',
          }}
        >
          <div className="p-8">
            {/* Header */}
            <div className="flex items-center gap-2 mb-6">
              <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-emerald-500 to-teal-500 flex items-center justify-center">
                <Leaf size={16} className="text-white" />
              </div>
              <span className="text-lg font-bold text-white">EcoTwin</span>
            </div>

            {/* Eco Score */}
            <div className="text-center mb-6">
              <p className="text-sm text-slate-400 mb-2">Eco Score</p>
              <p className="text-6xl font-bold bg-gradient-to-r from-emerald-400 to-teal-400 bg-clip-text text-transparent">
                {ecoScore}
              </p>
              <p className={`text-sm font-semibold ${rank.color} mt-2`}>
                {rank.label}
              </p>
            </div>

            {/* Stats Grid */}
            <div className="grid grid-cols-2 gap-3 mb-6">
              <div className="bg-white/[0.05] rounded-xl p-3 text-center">
                <Globe size={16} className="text-purple-400 mx-auto mb-1" />
                <p className="text-lg font-bold text-white">{earthsNeeded}</p>
                <p className="text-xs text-slate-500">Earths Needed</p>
              </div>
              <div className="bg-white/[0.05] rounded-xl p-3 text-center">
                <TreePine size={16} className="text-green-400 mx-auto mb-1" />
                <p className="text-lg font-bold text-white">{treesEquiv}</p>
                <p className="text-xs text-slate-500">Trees Equivalent</p>
              </div>
              <div className="bg-white/[0.05] rounded-xl p-3 text-center">
                <Award size={16} className="text-emerald-400 mx-auto mb-1" />
                <p className="text-lg font-bold text-white">{(carbon.total / 1000).toFixed(1)}t</p>
                <p className="text-xs text-slate-500">Carbon / Year</p>
              </div>
              <div className="bg-white/[0.05] rounded-xl p-3 text-center">
                <Share2 size={16} className="text-teal-400 mx-auto mb-1" />
                <p className="text-lg font-bold text-white">{(waterFootprint / 1000000).toFixed(1)}M</p>
                <p className="text-xs text-slate-500">Liters Water</p>
              </div>
            </div>

            {/* Footer */}
            <div className="text-center">
              <p className="text-xs text-slate-600">
                Generated by EcoTwin • ecotwin.app
              </p>
            </div>
          </div>
        </div>
      </div>

      {/* Download Button */}
      <div className="text-center">
        <Button
          variant="primary"
          icon={Download}
          onClick={handleDownload}
          disabled={isGenerating}
        >
          {isGenerating ? 'Generating...' : 'Download PNG'}
        </Button>
      </div>
    </div>
  );
}
