import { motion } from 'framer-motion';
import { Clock, BookOpen, TreePine, Droplets, Zap } from 'lucide-react';
import { GlassCard } from '../shared/UIComponents';

export default function FutureTimeline({ savings, customAiResult }) {
  if (!savings && !customAiResult) return null;

  // Use AI results if available, otherwise use algorithmic savings
  const renderYearCard = (title, yearKey, colorClass, gradientClass, aiImpactText) => {
    const data = savings?.[yearKey];
    
    return (
      <GlassCard className={`relative overflow-hidden ${gradientClass}`}>
        <p className={`text-xs font-semibold uppercase tracking-wider mb-3 ${colorClass}`}>
          {title}
        </p>
        
        {customAiResult ? (
          <p className="text-sm text-slate-300 leading-relaxed italic border-l-2 pl-3 border-emerald-500/30">
            "{aiImpactText}"
          </p>
        ) : data ? (
          <div className="space-y-3 relative z-10">
            <div className="flex justify-between items-center">
              <span className="text-xs text-slate-400">Carbon Prevented</span>
              <span className="text-sm font-bold text-white">{(data.carbonReduced / 1000).toFixed(1)}t</span>
            </div>
            {data.waterSaved > 0 && (
              <div className="flex justify-between items-center">
                <span className="text-xs text-slate-400">Water Saved</span>
                <span className="text-sm font-bold text-blue-400">{(data.waterSaved / 1000).toFixed(1)}k L</span>
              </div>
            )}
            {data.wasteReduced > 0 && (
              <div className="flex justify-between items-center">
                <span className="text-xs text-slate-400">Waste Prevented</span>
                <span className="text-sm font-bold text-orange-400">{data.wasteReduced} kg</span>
              </div>
            )}
            <div className="flex justify-between items-center">
              <span className="text-xs text-slate-400">Trees Equivalent</span>
              <span className="text-sm font-bold text-green-400">{data.treesEquivalent} 🌳</span>
            </div>
          </div>
        ) : null}
      </GlassCard>
    );
  };

  return (
    <div className="space-y-6">
      <div className="flex items-center gap-2 mb-2">
        <Clock size={20} className="text-emerald-400" />
        <h3 className="text-xl font-bold text-white">Environmental Future Timeline</h3>
      </div>

      {/* Timeline Visualizer */}
      <div className="relative pl-4 sm:pl-0">
        <div className="hidden sm:block absolute top-[18px] left-0 right-0 h-0.5 bg-gradient-to-r from-emerald-500/20 via-teal-500/40 to-cyan-500/20" />
        
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-6 relative">
          <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.1 }}>
            <div className="hidden sm:flex absolute -top-[5px] left-1/2 w-3 h-3 rounded-full bg-emerald-400 shadow-[0_0_10px_#10b981]" />
            {renderYearCard(
              "By 2027 (1 Year)", 
              "year1", 
              "text-emerald-400", 
              "hover:bg-emerald-500/5",
              customAiResult?.oneYearImpact
            )}
          </motion.div>
          
          <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.2 }}>
            <div className="hidden sm:flex absolute -top-[5px] left-1/2 w-3 h-3 rounded-full bg-teal-400 shadow-[0_0_10px_#14b8a6]" />
            {renderYearCard(
              "By 2031 (5 Years)", 
              "year5", 
              "text-teal-400", 
              "hover:bg-teal-500/5",
              customAiResult?.fiveYearImpact
            )}
          </motion.div>
          
          <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.3 }}>
            <div className="hidden sm:flex absolute -top-[5px] left-1/2 w-3 h-3 rounded-full bg-cyan-400 shadow-[0_0_10px_#06b6d4]" />
            {renderYearCard(
              "By 2036 (10 Years)", 
              "year10", 
              "text-cyan-400", 
              "hover:bg-cyan-500/5",
              customAiResult?.tenYearImpact
            )}
          </motion.div>
        </div>
      </div>

      {/* AI Future Story (If generated by Gemini) */}
      {customAiResult?.futureStory && (
        <motion.div initial={{ opacity: 0, scale: 0.95 }} animate={{ opacity: 1, scale: 1 }} transition={{ delay: 0.5 }}>
          <GlassCard glow className="bg-gradient-to-br from-indigo-500/10 via-purple-500/5 to-emerald-500/10 border-indigo-500/30 mt-8 relative overflow-hidden">
            <div className="absolute top-0 right-0 w-64 h-64 bg-emerald-500/10 blur-[100px] rounded-full pointer-events-none" />
            
            <div className="flex items-center gap-3 mb-4">
              <div className="w-10 h-10 rounded-xl bg-indigo-500/20 flex items-center justify-center">
                <BookOpen size={20} className="text-indigo-400" />
              </div>
              <div>
                <p className="text-xs text-indigo-400 uppercase tracking-widest font-semibold">AI Prediction</p>
                <h4 className="text-lg font-bold text-white">Your Future Story</h4>
              </div>
            </div>
            
            <p className="text-slate-300 leading-relaxed relative z-10 text-[15px]">
              {customAiResult.futureStory}
            </p>
          </GlassCard>
        </motion.div>
      )}
    </div>
  );
}
